
# #YESWECAN
# root@bb46a513a994:/# cat /etc/nginx/nginx.conf 
# user www-data;
# worker_processes auto;
# pid /run/nginx.pid;
# error_log /var/log/nginx/error.log;
# include /etc/nginx/modules-enabled/*.conf;

events {
   worker_connections 768;
   # multi_accept on;
}

http {
    server {
    	listen 443 ssl;
    	ssl_protocols TLSv1.2 TLSv1.3;
    	ssl_certificate /etc/nginx/ssl/inception.crt;
    	ssl_certificate_key /etc/nginx/ssl/inception.key;

        #root /var/www/html; #wordpress quand actif
		server_name ldevoude.42.fr;
		# index index.php index.html index.htm;
		location / {
			try_files $uri $uri/ =404;
        }
		location ~ \.php$ {
			include snippets/fastcgi-php.conf;
			# fastcgi_pass wordpress:9000;
		}
    }
}