events	{

}

http	{
	server 	{
		#ssl/tls
    	listen              443 ssl;
		# listen              80 ssl;
		server_name			ldevoude.42.fr; #tochange into ldevoude.42.fr
		
		root         		/usr/share/nginx/html;
		index index.php index.html index.htm;
		location /foo/ {
  		try_files $uri $uri/ =404;
		}
		location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass wordpress:9000;
		}

    	ssl_certificate     /etc/nginx/ssl/inception.crt;
    	ssl_certificate_key /etc/nginx/ssl/inception.key;
		ssl_session_timeout 10m;
    	ssl_protocols       TLSv1.2 TLSv1.3;
    	#ssl_ciphers        HIGH:!aNULL:!MD5;
	}
}