server {
	#ssl/tls
    listen              443 ssl;
    server_name         www.example.com;
    ssl_certificate     /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
	

    ssl_ciphers         HIGH:!aNULL:!MD5;
	domain_name			ldevoude.42.fr


    ...
}