# services:
#   mariadb:
#     image: mariadb
#     restart: always
#     # environment:
#     #   MYSQL_ROOT_PASSWORD: secret
#     volumes:
#       - ./data:/var/lib/mysql
#     ports:
#       -3306:3306


services: 
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfiletest
    ports:
      - 443:443
    #here I need to find out what kind of healthcheck
      #to do with nginx.
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      #change localhost if necessary
      test: ["CMD", "curl", "-k", "https://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    #think about what kind of restart we need
    volumes:
      - wordpress_data:/var/www/html
    #network
    restart: unless-stopped
    networks:
    - inception


  #same for wordpress

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    #healthcheck
    restart: unless-stopped
    networks:
    - inception

  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    #environment:?
    #healthcheck?

    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    networks:
    - inception
    

networks:
  inception: #name of the network
    driver: bridge #?
    ipam: #ip adress managment
      config:
        - subnet: "172.20.0.0/16" #ip here between quotes