volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ldevoude/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ldevoude/data/mariadb
services:

  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    environment:
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${SQL_USER}
      WORDPRESS_DB_PASSWORD: ${SQL_PASSWORD}
      WORDPRESS_DB_NAME: ${SQL_DATABASE}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD","php-fpm8.2", "-t"]
      interval: 30s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    networks:
    - inception

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - 443:443
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-k", "https://ldevoude.42.fr"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    networks:
    - inception

    
networks:
  inception:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"