[www]
user = www-data
group = www-data #?

listen = 9000

listen.owner = www-data
listen.group = www-data
listen.mode = www-data

# picked that as it is default balance as it adjust worker processes based on the current trafic
pm = dynamic

# (total RAM - (DB etc) / process size)
pm.max_children = 10
# max_child x 0.25
pm.start_servers = 2
# max_child x 0.25
pm.min_spare_servers = 2
# max_child x 0.75
pm.max_spare_servers = 7
# 500 = saf for most app
pm.max_requests = 500

